markdown: rdiscount
permalink: /:title/
url: http://aliveaway.github.io
name: roman.youlv
author: youlv
qq: 1152172304
email: youlv2014@gmail.com
duoshuo: youlv
beian: 浙ICP备12026616号
cnzz: 119959
weibo: 2168469240
github: aliveaway
pygments: true
safe: true
paginate: 20
about: "这里是 youlv 的个人博客，创建于 2016 年。欢迎观赏、建议、拍砖……"
